### PR TITLE
Misc bugfixes for the docker plugin

### LINKED ISSUE #266: During dockerBuild, dockerCopyMappings doesn't retain file flags
The ENTRYPOINT directive requires its target to be executable.  If this target is a script copied through `dockerCopyMappings`, the file doesn't retain its +x flag.  Though the build succeeds, this ultimately causes the container to fail to start.

The workaround from Jesse works:
```dockerfile
ENTRYPOINT ["sh", "-c", "chmod +x my_script; exec my_script"]
```

### PR DESCRIPTION
**Pull request by jkinkead**
This fixes #266, #268, and a few cache key bugs.

### CODE REVIEW

File: src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala [hunk 1]
```diff
@@ -625,11 +633,23 @@ $DOCKERFILE_SIGIL
...
           if (source.isDirectory) {
             IO.createDirectory(destination)
-            IO.copyDirectory(source, destination)
+            val toCopy = PathFinder(source).***.pair(Path.rebase(source, destination))
+            IO.copy(toCopy)
+            toCopy.foreach {
+              case (source, destination) =>
+                if (source.canExecute) {
+                  destination.setExecutable(true)
+                }
```
Comment (ColinArenz) [inline src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala]: I'd replace this `if` block with `destination.setExecutable(source.canExecute)`.  That way if we'll sync up the flag if the destination was marked executable, but the source's flag has changed.

File: src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala [hunk 2]
```diff
@@ -649,29 +669,34 @@ $DOCKERFILE_SIGIL
...
       }
 
-      // Find the git commits / random IDs for the current project and local dependencies.
-      val unstableContentsCommits = {
-        Def.taskDyn(gitCommitOrGuid.all(HelperDefs.dependencyFilter.value)).value :+
-          gitCommitOrGuid.value
+      // Find the git commits for the current project and local dependencies, since this is more
+      // stable than a hash of the contents.
+      val unstableContentsCommits: Seq[Option[String]] = {
+        (Def.taskDyn(gitCommitIfClean.all(HelperDefs.dependencyFilter.value)).value :+
```
Comment (ColinArenz) [inline src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala]: I really like that you're doing this by project, so an unrelated change won't dirty it.

Comment (jkinkead) [inline src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala]: There are some edge-cases where this breaks, unfortunately. Notably, this doesn't take into account changes in root sbt settings (settings in the root `build.sbt` or root `project/*`). However, these would have to be changes which affected the compiled code but not either dependencies or the Dockerfile - so, things like updates to the docker plugin...

:P

File: src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala (hunk 1 above)
Comment (jkinkead) [inline src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala]: I think the `copy` line beforehand will replace the target, so this might work regardless - but this is cleaner. Updated!
